name: vote
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/vote.dart
environment:
  sdk: '>=1.12.0-dev.5.0 <2.0.0'
dependencies:
  bot: '>=0.26.0'
  bot_web: '>=0.21.0'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  test: '>=0.12.0 <0.13.0'
