name: vote_demo
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.0.0
  url_launcher: ^6.0.9
  vote: any
  vote_widgets: any

dev_dependencies:
  build_runner: ^2.0.5
  build_web_compilers: ^3.0.0
  pedantic: ^1.0.0

dependency_overrides:
  vote:
    path: ../vote
  vote_widgets:
    path: ../vote_widgets

flutter:
  uses-material-design: true

  fonts:
  - family: OverpassMono
    fonts:
    - asset: assets/fonts/OverpassMono-Bold.ttf
  - family: RobotoMono
    fonts:
    - asset: assets/fonts/RobotoMono-Regular.ttf
