name: knarly

environment:
  sdk: '>=2.5.0-dev.1.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  flutter:
    sdk: flutter
  provider: ^3.1.0
  vote:
    path: ../vote

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: RobotoMono
    fonts:
    - asset: assets/fonts/RobotoMono-Regular.ttf
